# Generated by Django 3.2.9 on 2022-11-25 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='street',
        ),
    ]
