# Generated by Django 3.2.9 on 2022-11-28 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20221125_1724'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Продукты'},
        ),
    ]
