# Generated by Django 4.1.3 on 2022-11-29 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("contacts", "0001_initial"),
        ("esn", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="objectmodel",
            name="contacts",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="contacts",
                to="contacts.contacts",
            ),
        ),
    ]
