# Generated by Django 3.2.9 on 2022-11-25 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esn', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dealership',
            name='employees',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='dealership',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='distributor',
            name='employees',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='distributor',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='factory',
            name='employees',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='individualentrepreneur',
            name='employees',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='individualentrepreneur',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='largeretailchain',
            name='employees',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='largeretailchain',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
