# Generated by Django 3.2.9 on 2022-11-26 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esn', '0002_auto_20221125_1724'),
    ]

    operations = [
        migrations.AddField(
            model_name='dealership',
            name='debt',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='distributor',
            name='debt',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='individualentrepreneur',
            name='debt',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='largeretailchain',
            name='debt',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, null=True),
        ),
    ]
