# Generated by Django 4.1.3 on 2022-11-30 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("esn", "0002_alter_objectmodel_contacts"),
    ]

    operations = [
        migrations.AddField(
            model_name="objectmodel",
            name="provider",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="esn.objectmodel",
            ),
        ),
    ]
