# Generated by Django 3.2.9 on 2022-11-28 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('esn', '0003_auto_20221126_1628'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dealership',
            options={'verbose_name': 'Дилерский центр'},
        ),
        migrations.AlterModelOptions(
            name='distributor',
            options={'verbose_name': 'Дистрибьютор'},
        ),
        migrations.AlterModelOptions(
            name='factory',
            options={'verbose_name': 'Завод'},
        ),
        migrations.AlterModelOptions(
            name='individualentrepreneur',
            options={'verbose_name': 'Индивидуальный предприниматель'},
        ),
        migrations.AlterModelOptions(
            name='largeretailchain',
            options={'verbose_name': 'Крупная розничная сеть'},
        ),
    ]
