# Generated by Django 4.1.4 on 2022-12-07 10:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_alter_product_options"),
        ("contacts", "0004_alter_address_country"),
        ("employees", "0002_alter_employees_address"),
        ("esn", "0005_alter_objectmodel_provider"),
    ]

    operations = [
        migrations.AlterField(
            model_name="objectmodel",
            name="contacts",
            field=models.OneToOneField(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="contacts",
                to="contacts.contacts",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="objectmodel",
            name="employees",
            field=models.ManyToManyField(
                related_name="employees", to="employees.employees"
            ),
        ),
        migrations.AlterField(
            model_name="objectmodel",
            name="product",
            field=models.ManyToManyField(related_name="product", to="products.product"),
        ),
    ]
