# Generated by Django 4.1.4 on 2022-12-15 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("esn", "0006_alter_objectmodel_contacts_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="objectmodel",
            name="type",
            field=models.CharField(
                choices=[
                    ("0", "Factory"),
                    ("1", "Distributor"),
                    ("2", "Large_retail_chain"),
                    ("3", "December"),
                    ("4", "Individual_entrepreneur"),
                ],
                default="FACTORY",
                max_length=20,
            ),
        ),
    ]
