# Generated by Django 4.1.4 on 2022-12-19 09:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("contacts", "0005_alter_contacts_address"),
        ("employees", "0002_alter_employees_address"),
        ("products", "0002_alter_product_options"),
        ("esn", "0007_alter_objectmodel_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="objectmodel",
            name="contacts",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="objects",
                to="contacts.contacts",
            ),
        ),
        migrations.AlterField(
            model_name="objectmodel",
            name="employees",
            field=models.ManyToManyField(
                related_name="objects", to="employees.employees"
            ),
        ),
        migrations.AlterField(
            model_name="objectmodel",
            name="product",
            field=models.ManyToManyField(related_name="objects", to="products.product"),
        ),
        migrations.AlterField(
            model_name="objectmodel",
            name="type",
            field=models.CharField(
                choices=[
                    (0, "Factory"),
                    (1, "Distributor"),
                    (2, "Large_retail_chain"),
                    (3, "December"),
                    (4, "Individual_entrepreneur"),
                ],
                default=0,
                max_length=20,
            ),
        ),
    ]
