# Generated by Django 4.1.4 on 2022-12-19 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_alter_product_options"),
        ("contacts", "0005_alter_contacts_address"),
        ("employees", "0002_alter_employees_address"),
        ("esn", "0008_alter_objectmodel_contacts_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="objectmodel",
            name="contacts",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="objects_model",
                to="contacts.contacts",
            ),
        ),
        migrations.AlterField(
            model_name="objectmodel",
            name="employees",
            field=models.ManyToManyField(
                related_name="objects_model", to="employees.employees"
            ),
        ),
        migrations.AlterField(
            model_name="objectmodel",
            name="product",
            field=models.ManyToManyField(
                related_name="objects_model", to="products.product"
            ),
        ),
    ]
