# Generated by Django 4.1.4 on 2022-12-30 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("esn", "0009_alter_objectmodel_contacts_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="objectmodel",
            name="type",
            field=models.CharField(
                choices=[
                    ("FA", "Factory"),
                    ("DI", "Distributor"),
                    ("LRC", "Large_retail_chain"),
                    ("DE", "December"),
                    ("IE", "Individual_entrepreneur"),
                ],
                default="FA",
                max_length=20,
            ),
        ),
    ]
