# Generated by Django 4.1.3 on 2022-11-29 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contacts", "0002_alter_contacts_address"),
    ]

    operations = [
        migrations.AlterField(
            model_name="address",
            name="country",
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
