# Generated by Django 4.1.4 on 2022-12-19 09:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("contacts", "0004_alter_address_country"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contacts",
            name="address",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="contacts",
                to="contacts.address",
            ),
        ),
    ]
