# Generated by Django 4.1.4 on 2022-12-07 10:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("contacts", "0004_alter_address_country"),
        ("employees", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employees",
            name="address",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="contacts_employee",
                to="contacts.contacts",
            ),
            preserve_default=False,
        ),
    ]
